name: Install and setup Terminus
on: workflow_call
  inputs:
    terminus-version:
      description: A specific version of Terminus
      default: 3.0.8
  secrets:
    pantheon-machine-token:
      description: Pantheon machine token
      required: true
    pantheon-ssh-key:
      description: Pantheon SSH key
      required: true
      
- name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        
- name: Set up SSH
  run: |
    set -x
    mkdir ${HOME}/.ssh && chmod 700 ${HOME}/.ssh
    echo -e "Host *.drush.in\n    StrictHostKeyChecking no" > ${HOME}/.ssh/config
    echo -e "${{ secrets.PANTHEON_SSH_KEY }}" > ${HOME}/.ssh/id_rsa
    chmod 600 ${HOME}/.ssh/*

- name: Install and authenticate Terminus
  uses: pantheon-systems/terminus-github-actions@release/v1
  with:
    pantheon-machine-token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}
    terminus-version: ${{ inputs.terminus-version }}
